### ISSUE TITLE
Create a SHORT post about how the TEC uses the Trusted Seed

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/content-distribution#47]
## 📋   Anything to add?

This was requested by Z.

## 🎉   Subtasks

- [ ] The TEC CHOSE to use the Trusted Seed as the Hatchers (Expand and link)
- [ ] The TEC CHOSE to use the Membership Ratio of ________ (Expand and link)
- [ ] Discuss the side effect of using the amplitude of the CSTK Score and how people can pay more dues within their maxTrustScore (Expand and Link)

## 🤼‍♂️   Reviewer

@

**Comment by chuygarcia92** [comment]
Some advances & updates:

https://hackmd.io/@1sBtuDmrRBG360k8-EXf2A/By5jl-VYu/edit 

Any thoughts? @tamarandom @GriffGreen

**Comment by tamarandom** [comment]
@chuygarcia92 and I are talking about this issue which we agree to close it.

For the first point, there is this article: https://medium.com/commonsstack/whats-in-a-hatch-3799a398243a

For the second, that will be part of the Hatcher Handbook #736

And for the third point, it's being covered by a planned forum post (see https://docs.google.com/document/d/1nCY3VTIZmeNeQi5mJ8pf3xaJ1VKj6wS6NqXRPz6tVao/edit)
