### ISSUE TITLE
TEC C&D Request - Forum Posts for Commons Upgrade

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#67]
**1- What is the content?**
- [ ] Graphic
- [ ] Meme
- [ ] Tweet
- [X] Campaign for a specific event
- [ ] Article/Blog Post
- [ ] Videos, Podcasts, Spotlight Interviews, etc.
- [ ] News (Recaps, mailing lists, etc)

**2- When is the distribution of this content due?**
When the hatch opens

**3- What is the purpose of this content?**
- [X] Informative
- [ ] Call-To-Action (focused on community)
- [ ] Engage/Invite (meant for wider audiences outside TEC & friends)

**4- Is this content finished?**
- [ ] Yes
- [X] No, it needs to be made

**5- Additional notes**
Needed forum posts for Commons Upgrade parameters
